import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import AssignifyLogo from "@/components/AssignifyLogo";

const Terms = () => {
  const updated = "16 April 2026";

  return (
    <div className="min-h-screen bg-[#070f0a] text-white" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
      {/* Nav */}
      <nav className="border-b border-white/5 bg-[#070f0a]/95 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 text-white/50 hover:text-white text-sm transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to home
          </Link>
          <AssignifyLogo size="sm" variant="light" showText={true} />
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <p className="text-xs text-[#1abb9b] font-bold tracking-widest uppercase mb-3">LEGAL</p>
          <h1 className="text-4xl md:text-5xl font-normal mb-4 text-white"
            style={{ fontFamily: "'Instrument Serif', serif" }}>
            Terms of Service
          </h1>
          <p className="text-white/40 text-sm">Last updated: {updated}</p>
        </div>

        {/* Content */}
        <div className="space-y-10 text-white/70 text-sm leading-relaxed">

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">1. Acceptance of Terms</h2>
            <p>
              By creating an account or using Assignify ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
            <p>
              These Terms apply to all users of Assignify, including lecturers who create accounts and students who submit through assignment links.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">2. Description of Service</h2>
            <p>
              Assignify is an online assignment management platform that allows lecturers to create assignments, collect student file submissions, and generate CA collation reports. The service is currently free for all lecturers.
            </p>
            <p>
              Students do not require accounts to submit assignments. They access submission forms through unique links generated by their lecturers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">3. Eligibility</h2>
            <p>
              Assignify is intended for use by lecturers and educators at Nigerian universities and educational institutions. By registering, you confirm that:
            </p>
            <ul className="space-y-1.5 pl-5 list-disc list-outside">
              <li>You are a lecturer, educator, or academic staff member</li>
              <li>The information you provide during registration is accurate and truthful</li>
              <li>You are at least 18 years of age</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">4. Lecturer accounts and responsibilities</h2>
            <p>As a lecturer using Assignify, you are responsible for:</p>
            <ul className="space-y-1.5 pl-5 list-disc list-outside">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activity that occurs under your account</li>
              <li>Ensuring that your use of the Service complies with your institution's academic policies</li>
              <li>Informing students that their submitted data is being collected through this platform</li>
              <li>Only sharing assignment links with students who are legitimately enrolled in your course</li>
            </ul>
            <p>
              You must not share your login credentials with any other person. If you believe your account has been compromised, contact us immediately at{" "}
              <a href="mailto:support@assignify.com.ng" className="text-[#1abb9b] hover:underline">support@assignify.com.ng</a>.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">5. Acceptable use</h2>
            <p>You agree not to use Assignify to:</p>
            <ul className="space-y-1.5 pl-5 list-disc list-outside">
              <li>Upload or distribute any content that is unlawful, harmful, or violates any third-party rights</li>
              <li>Attempt to gain unauthorized access to any part of the Service or its infrastructure</li>
              <li>Collect or harvest other users' data without their knowledge or consent</li>
              <li>Engage in any activity that disrupts or interferes with the Service</li>
              <li>Use the Service for commercial purposes not related to education without our written consent</li>
              <li>Submit false information or impersonate any person or institution</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">6. File uploads and content</h2>
            <p>
              Students may upload PDF or Word documents (up to 10MB) through assignment submission forms. You, as the lecturer, are responsible for ensuring that submission links are only shared with legitimate students.
            </p>
            <p>
              Assignify does not review the content of uploaded files. You are responsible for the academic integrity of your assignments and submissions. We reserve the right to remove any content that violates these Terms or applicable law.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">7. Intellectual property</h2>
            <p>
              All student-submitted files remain the intellectual property of the respective students. By submitting through Assignify, students grant the platform a limited, non-exclusive licence to store and display the file to the assignment-owning lecturer only.
            </p>
            <p>
              The Assignify name, logo, and platform code are proprietary. You may not reproduce or use them without written permission from the Assignify team.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">8. Availability and service changes</h2>
            <p>
              We will make reasonable efforts to keep Assignify available and operational. However, we do not guarantee 100% uptime. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.
            </p>
            <p>
              We reserve the right to modify, suspend, or discontinue any part of the Service at any time. We will provide reasonable notice of significant changes where possible.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">9. Disclaimers and limitation of liability</h2>
            <p>
              Assignify is provided "as is" without warranties of any kind, express or implied. We do not guarantee that the Service will be error-free or uninterrupted.
            </p>
            <p>
              To the maximum extent permitted by applicable law, Assignify and its operator shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including loss of data or academic records.
            </p>
            <p>
              You are solely responsible for maintaining copies of important submissions and records. We strongly recommend downloading submissions regularly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">10. Account termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time if you violate these Terms or engage in conduct that is harmful to other users or the platform.
            </p>
            <p>
              You may delete your account at any time by contacting us at{" "}
              <a href="mailto:support@assignify.com.ng" className="text-[#1abb9b] hover:underline">support@assignify.com.ng</a>.
              Upon deletion, your data and all associated submissions will be permanently removed within 30 days.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">11. Governing law</h2>
            <p>
              These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes arising from use of the Service shall be subject to the exclusive jurisdiction of Nigerian courts.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">12. Changes to these Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify registered users of material changes by email or by displaying a notice on the platform. Continued use of the Service after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-white text-lg font-semibold">13. Contact</h2>
            <p>
              For questions about these Terms, contact us at:{" "}
              <a href="mailto:support@assignify.com.ng" className="text-[#1abb9b] hover:underline">support@assignify.com.ng</a>
            </p>
          </section>
        </div>

        {/* Footer nav */}
        <div className="mt-16 pt-8 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-white/30">
          <p>© 2026 Assignify</p>
          <div className="flex items-center gap-6">
            <Link to="/privacy" className="hover:text-white/60 transition-colors">Privacy Policy</Link>
            <Link to="/" className="hover:text-white/60 transition-colors">Back to home</Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;